version: '2.0'

services:
  jupyter_datascience:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
    ports:
      - '8888:8888'
    volumes:
      - '.:/notebooks'
volumes:
  mongo: